apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: secretpod
  name: secretpod
spec:
  containers:
  - image: keshavprasad/shell-app:0.0.2
    name: secretpod
    env:
      - name: SECRETNAME
        valueFrom:
          secretKeyRef:
            name: literalsecret
            key: SECRETNAME
      - name: VAR1
        valueFrom:
          secretKeyRef:
            name: secretenvfile
            key: SUPER
      - name: VAR2
        valueFrom:
          secretKeyRef:
            name: secretenvfile
            key: COOL
    resources: {}
    volumeMounts:
    - name: super-secret
      mountPath: "/keepout/"
      readOnly: true
  volumes:
  - name: super-secret
    secret:
      secretName: secretfile
  dnsPolicy: ClusterFirst
  restartPolicy: OnFailure