apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: shellappcm
  name: shellappcm
spec:
  containers:
  - image: keshavprasad/shell-app:0.0.1
    name: shellappcm
    resources: {}
    volumeMounts:
    - name: envmount
      mountPath: /envconfig
      subPath: envconfig
  volumes:
  - name: envmount
    configMap:
      name: envfile-cm
      items:
      - key: envfile
        path: envconfig
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
