version: "3.9"
services:
  goserver:
    build:
     context: .
     dockerfile: DockerfileGo
    ports:
      - "8090:8090"
  pyserver:
    build:
     context: .
     dockerfile: DockerfilePython
    ports:
      - "8000:8000"
  shellapp:
    build:
     context: .
     dockerfile: DockerfileShell
