apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: shellappenv
  name: shellappenv
spec:
  containers:
  - image: keshavprasad/shell-app:0.0.1
    env:
    - name: FIRSTNAME
      value: Scooby
    - name: LASTNAME
      value: Bravo
    name: shellappenv
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
